#--------------------------------------------------------------
# Simple AWS CodeBuild Config File
#
# Copyleft (c) by Denis Astahov
#--------------------------------------------------------------
version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION : "eu-north-1"
#    AWS_ACCOUNT_ID    : "id--"
    ECR_REPO_NAME      : "webapp"
    ECR_IMAGE_TAG      : "latest"
  parameter-store:
    AWS_ACCOUNT_ID     : "MY_ACCOUNT_ID"

phases:
  install:
    commands:
      - echo "Check aws and git version"
      - aws --version
      - git --version
      - docker --version
      - echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
      - echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
      - export AWS_DEFAULT_REGION=eu-north-1
      - echo "--------------------------------"

  pre_build:
    commands:
      - echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
      - echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
      - echo "Login to AWS ECR and get commit id"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 735207908250.dkr.ecr.eu-north-1.amazonaws.com  
      - COMMIT_ID=$(git rev-parse --short HEAD)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_NAME:$ECR_IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$ECR_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$ECR_IMAGE_TAG
      - docker tag $ECR_REPO_NAME:$ECR_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$COMMIT_ID

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$ECR_IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$COMMIT_ID